<a href="https://colab.research.google.com/github/andysun-1997/VQE-Sample-Problem-with-Cirq-and-TensorFlow-Quantum/blob/master/Direct_Eigenvalues_and_Eigenvectors_Calculations_of_H.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np
from numpy import linalg as LA

In [0]:
X = np.matrix(((0,1), (1,0)))

In [0]:
I = np.matrix(((1,0), (0,1)))

In [0]:
XI = np.kron(X,I)
XI

matrix([[0, 0, 1, 0],
        [0, 0, 0, 1],
        [1, 0, 0, 0],
        [0, 1, 0, 0]])

In [0]:
H1 = np.kron(XI, X)
H1

matrix([[0, 0, 0, 0, 0, 1, 0, 0],
        [0, 0, 0, 0, 1, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0, 1],
        [0, 0, 0, 0, 0, 0, 1, 0],
        [0, 1, 0, 0, 0, 0, 0, 0],
        [1, 0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 1, 0, 0, 0, 0],
        [0, 0, 1, 0, 0, 0, 0, 0]])

In [0]:
e1, v1 = LA.eigh(H1)
e1, v1

(array([-1., -1., -1., -1.,  1.,  1.,  1.,  1.]),
 matrix([[-0.70710678, -0.        , -0.        , -0.        ,  0.        ,
           0.        ,  0.        , -0.70710678],
         [ 0.        , -0.        ,  0.70710678, -0.        , -0.70710678,
           0.        ,  0.        ,  0.        ],
         [ 0.        , -0.70710678,  0.        , -0.        ,  0.        ,
          -0.70710678,  0.        ,  0.        ],
         [ 0.        ,  0.        ,  0.        ,  0.70710678,  0.        ,
           0.        , -0.70710678,  0.        ],
         [ 0.        ,  0.        , -0.70710678,  0.        , -0.70710678,
           0.        ,  0.        ,  0.        ],
         [ 0.70710678,  0.        ,  0.        ,  0.        ,  0.        ,
           0.        ,  0.        , -0.70710678],
         [-0.        ,  0.        , -0.        , -0.70710678,  0.        ,
           0.        , -0.70710678,  0.        ],
         [-0.        ,  0.70710678, -0.        ,  0.        ,  0.        ,


In [0]:
v1[:, 0]

matrix([[-0.70710678],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.        ],
        [ 0.70710678],
        [-0.        ],
        [-0.        ]])

In [0]:
Z = np.matrix(((1,0), (0,-1)))

In [0]:
ZI = np.kron(Z,I)

In [0]:
H2 = 0.9*np.kron(ZI,I)
H2

matrix([[ 0.9,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0.9,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0.9,  0. ,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0.9,  0. ,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0. , -0.9,  0. ,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0. ,  0. , -0.9,  0. ,  0. ],
        [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. , -0.9,  0. ],
        [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. , -0.9]])

In [0]:
e2, v2 = LA.eigh(H2)
e2, v2

(array([-0.9, -0.9, -0.9, -0.9,  0.9,  0.9,  0.9,  0.9]),
 matrix([[0., 0., 0., 0., 1., 0., 0., 0.],
         [0., 0., 0., 0., 0., 1., 0., 0.],
         [0., 0., 0., 0., 0., 0., 1., 0.],
         [0., 0., 0., 0., 0., 0., 0., 1.],
         [1., 0., 0., 0., 0., 0., 0., 0.],
         [0., 1., 0., 0., 0., 0., 0., 0.],
         [0., 0., 1., 0., 0., 0., 0., 0.],
         [0., 0., 0., 1., 0., 0., 0., 0.]]))

In [0]:
II = np.kron(I,I)

In [0]:
Y = np.matrix(((0,-1j), (1j,0)))
Y

matrix([[ 0.+0.j, -0.-1.j],
        [ 0.+1.j,  0.+0.j]])

In [0]:
H3 = -0.3*np.kron(II,Y)
H3

matrix([[0.+0.j , 0.+0.3j, 0.+0.j , 0.+0.j , 0.+0.j , 0.+0.j , 0.+0.j ,
         0.+0.j ],
        [0.-0.3j, 0.+0.j , 0.+0.j , 0.+0.j , 0.+0.j , 0.+0.j , 0.+0.j ,
         0.+0.j ],
        [0.+0.j , 0.+0.j , 0.+0.j , 0.+0.3j, 0.+0.j , 0.+0.j , 0.+0.j ,
         0.+0.j ],
        [0.+0.j , 0.+0.j , 0.-0.3j, 0.+0.j , 0.+0.j , 0.+0.j , 0.+0.j ,
         0.+0.j ],
        [0.+0.j , 0.+0.j , 0.+0.j , 0.+0.j , 0.+0.j , 0.+0.3j, 0.+0.j ,
         0.+0.j ],
        [0.+0.j , 0.+0.j , 0.+0.j , 0.+0.j , 0.-0.3j, 0.+0.j , 0.+0.j ,
         0.+0.j ],
        [0.+0.j , 0.+0.j , 0.+0.j , 0.+0.j , 0.+0.j , 0.+0.j , 0.+0.j ,
         0.+0.3j],
        [0.+0.j , 0.+0.j , 0.+0.j , 0.+0.j , 0.+0.j , 0.+0.j , 0.-0.3j,
         0.+0.j ]])

In [0]:
e3, v3 = LA.eigh(H3)
e3, v3

(array([-0.3, -0.3, -0.3, -0.3,  0.3,  0.3,  0.3,  0.3]),
 matrix([[-0.70710678+0.j        , -0.        +0.j        ,
          -0.        +0.j        , -0.        +0.j        ,
           0.        +0.j        ,  0.        +0.j        ,
           0.        +0.j        , -0.70710678+0.j        ],
         [ 0.        -0.70710678j,  0.        +0.j        ,
           0.        +0.j        ,  0.        +0.j        ,
           0.        +0.j        ,  0.        +0.j        ,
           0.        +0.j        ,  0.        +0.70710678j],
         [-0.        +0.j        , -0.70710678+0.j        ,
          -0.        +0.j        , -0.        +0.j        ,
           0.        +0.j        , -0.70710678+0.j        ,
           0.        +0.j        ,  0.        +0.j        ],
         [ 0.        +0.j        ,  0.        -0.70710678j,
           0.        +0.j        ,  0.        +0.j        ,
           0.        +0.j        ,  0.        +0.70710678j,
           0.        +0.j        ,  0. 

In [0]:
H = H1 + H2 + H3
H

matrix([[ 0.9+0.j ,  0. +0.3j,  0. +0.j ,  0. +0.j ,  0. +0.j ,
          1. +0.j ,  0. +0.j ,  0. +0.j ],
        [ 0. -0.3j,  0.9+0.j ,  0. +0.j ,  0. +0.j ,  1. +0.j ,
          0. +0.j ,  0. +0.j ,  0. +0.j ],
        [ 0. +0.j ,  0. +0.j ,  0.9+0.j ,  0. +0.3j,  0. +0.j ,
          0. +0.j ,  0. +0.j ,  1. +0.j ],
        [ 0. +0.j ,  0. +0.j ,  0. -0.3j,  0.9+0.j ,  0. +0.j ,
          0. +0.j ,  1. +0.j ,  0. +0.j ],
        [ 0. +0.j ,  1. +0.j ,  0. +0.j ,  0. +0.j , -0.9+0.j ,
          0. +0.3j,  0. +0.j ,  0. +0.j ],
        [ 1. +0.j ,  0. +0.j ,  0. +0.j ,  0. +0.j ,  0. -0.3j,
         -0.9+0.j ,  0. +0.j ,  0. +0.j ],
        [ 0. +0.j ,  0. +0.j ,  0. +0.j ,  1. +0.j ,  0. +0.j ,
          0. +0.j , -0.9+0.j ,  0. +0.3j],
        [ 0. +0.j ,  0. +0.j ,  1. +0.j ,  0. +0.j ,  0. +0.j ,
          0. +0.j ,  0. -0.3j, -0.9+0.j ]])

In [0]:
e, v = LA.eigh(H)
e, v

(array([-1.56204994, -1.56204994, -1.16619038, -1.16619038,  1.16619038,
         1.16619038,  1.56204994,  1.56204994]),
 matrix([[-1.16776447e-18+0.00000000e+00j,
          -2.40717012e-01+0.00000000e+00j,
          -3.76040841e-18-0.00000000e+00j,
          -3.48390673e-01-0.00000000e+00j,
           6.15227224e-01+0.00000000e+00j,
           1.09271211e-02+0.00000000e+00j,
          -6.64872062e-01+0.00000000e+00j,
          -6.79420396e-04+0.00000000e+00j],
         [ 8.54449685e-18+8.73770158e-17j,
          -2.22044605e-16+2.40717012e-01j,
           1.13926625e-17+1.14122939e-16j,
           0.00000000e+00-3.48390673e-01j,
          -1.66533454e-16+6.15227224e-01j,
          -1.26634814e-16+1.09271211e-02j,
          -1.11022302e-16+6.64872062e-01j,
          -6.12032126e-17+6.79420396e-04j],
         [ 2.40393039e-01-1.24846750e-02j,
           0.00000000e+00-5.93870207e-18j,
           3.46129922e-01+3.96249714e-02j,
           0.00000000e+00+2.73324840e-18j,
          -1.013

In [0]:
# Lowest eigenvalue and eigenstate
s0 = v[:,0]
e[0], s0

(-1.5620499351813313, matrix([[-1.16776447e-18+0.00000000e+00j],
         [ 8.54449685e-18+8.73770158e-17j],
         [ 2.40393039e-01-1.24846750e-02j],
         [-1.24846750e-02-2.40393039e-01j],
         [ 0.00000000e+00-5.03069808e-17j],
         [ 3.12326443e-17-2.56334905e-18j],
         [ 3.44832958e-02+6.63977577e-01j],
         [-6.63977577e-01+3.44832958e-02j]]))

In [0]:
# Lowest eigenvalue and eigenstate
s1 = v[:,1]
e[1], s1

(-1.5620499351813302, matrix([[-2.40717012e-01+0.00000000e+00j],
         [-2.22044605e-16+2.40717012e-01j],
         [ 0.00000000e+00-5.93870207e-18j],
         [ 0.00000000e+00-2.81206394e-17j],
         [ 1.76756462e-16-6.64872409e-01j],
         [ 6.64872409e-01+0.00000000e+00j],
         [-1.02330047e-17+4.00580276e-17j],
         [ 1.07951972e-16+1.19210121e-17j]]))